name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: fedora-latest

    steps:
    - name: Install required packages
      run: sudo dnf install wget xrdp -y

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract ngrok
      run: tar -xvf ngrok.tgz

    - name: Auth
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP
      run: sudo systemctl enable xrdp
    - run: sudo systemctl start xrdp

    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389
